find_package(Qt6 REQUIRED COMPONENTS Test Widgets Qml)

function(add_tool_test TEST_NAME)
    set(SOURCES ${ARGN})
    qt_add_executable(${TEST_NAME} ${SOURCES})
    target_link_libraries(${TEST_NAME} PRIVATE Qt6::Test Qt6::Widgets Qt6::Core Qt6::Core5Compat)
    target_include_directories(${TEST_NAME} PRIVATE
        ${CMAKE_SOURCE_DIR}/src
        ${CMAKE_SOURCE_DIR}/tests/testutils
    )
    add_test(NAME ${TEST_NAME} COMMAND ${TEST_NAME})
endfunction()

add_subdirectory(test_optionContainer)
add_subdirectory(test_notDoAnything)
add_subdirectory(test_addAffix)
add_subdirectory(test_setAlias)
add_subdirectory(test_removeBlank)
add_subdirectory(test_removeAffix)
add_subdirectory(test_removeDuplicate)
add_subdirectory(test_removeSpecificEntries)
add_subdirectory(test_mergeOto)
add_subdirectory(test_copyOrReplaceByAlias)
add_subdirectory(test_overlapBatchSet)
add_subdirectory(test_preCenteredChangeValue)
add_subdirectory(test_trimAroundSpecificValue)
add_subdirectory(test_tempoTransform)
add_subdirectory(test_cvvcPartSplit)
add_subdirectory(test_vowelCrossfading)
add_subdirectory(test_replaceFileName)
add_subdirectory(test_toolManager)
add_subdirectory(test_chain)
add_subdirectory(test_convertPlusMinusRight)
add_subdirectory(test_jsScript)
add_subdirectory(test_otoFileReader)
